version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errorlint
    - gosec
    - misspell
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      - path: internal/testutil/
        linters:
          - errcheck
          - gosec
