version: "3"

tasks:
  build:
    desc: Собрать бинарный файл
    cmds:
      - go build -o xray-health-exporter .

  test:
    desc: Запустить тесты
    cmds:
      - go test -v -cover ./...

  test-race:
    desc: Запустить тесты с детектором гонок
    cmds:
      - go test -v -race ./...

  test-coverage:
    desc: Запустить тесты с покрытием и сгенерировать отчет
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
      - >
        echo "📊 Для HTML отчета запустите: go tool cover -html=coverage.out"

  coverage-html:
    desc: Открыть HTML отчет о покрытии
    deps: [test-coverage]
    cmds:
      - go tool cover -html=coverage.out

  ci-test:
    desc: Запустить тесты как в CI (с покрытием и race detector)
    cmds:
      - go fmt ./...
      - go build -v -o xray-health-exporter .
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - go tool cover -func=coverage.out | tail -1
      - echo "✅ Все проверки CI пройдены!"

  install-hooks:
    desc: Установить git pre-commit хуки
    cmds:
      - pre-commit install
      - echo "✅ Pre-commit хуки установлены!"

  clean:
    desc: Очистить артефакты сборки
    cmds:
      - rm -f xray-health-exporter coverage.txt

  run:
    desc: Запустить приложение
    cmds:
      - go run .

  docker-build:
    desc: Собрать Docker образ
    cmds:
      - docker build -t xray-health-exporter .

  docker-build-multi:
    desc: Собрать мультиплатформенный Docker образ
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t xray-health-exporter .

  docker-run:
    desc: Запустить Docker контейнер
    deps: [docker-build]
    cmds:
      - docker run --rm -v $(pwd)/config.yaml:/app/config.yaml:ro -p 9090:9090 xray-health-exporter
